from enum import Enum


class Text_Type(Enum):
    CAMPAIGN = 1
    SUBRACE = 2
    DESCRIPTION = 3
    CATEGORY = 4
    CATEGORY_DESCRIPTION = 5
    CATEGORY_EXPANSION = 6
    SUBCATEGORY = 7
    SUBCATEGORY_DESCRIPTION = 8
    TABLE_NAME = 9
    TABLE = 10
